# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.transaction_schema_data import TransactionSchemaData

class TestTransactionSchemaData(unittest.TestCase):
    """TransactionSchemaData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionSchemaData:
        """Test TransactionSchemaData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionSchemaData`
        """
        model = TransactionSchemaData()
        if include_optional:
            return TransactionSchemaData(
                id_transaction_integrator = '',
                duration = 56,
                price_second = 1.337,
                text_call = '',
                id_user = '',
                amount = 1.337,
                invoice_id = '',
                invoice_number = '',
                inn = '',
                phone = '',
                invoice_url = '',
                remains = 1.337,
                act_url = ''
            )
        else:
            return TransactionSchemaData(
                invoice_id = '',
                invoice_url = '',
                remains = 1.337,
        )
        """

    def testTransactionSchemaData(self):
        """Test TransactionSchemaData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
