# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.testing_schema import TestingSchema

class TestTestingSchema(unittest.TestCase):
    """TestingSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestingSchema:
        """Test TestingSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestingSchema`
        """
        model = TestingSchema()
        if include_optional:
            return TestingSchema(
                count_testing_day = 56
            )
        else:
            return TestingSchema(
        )
        """

    def testTestingSchema(self):
        """Test TestingSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
