# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.status_transaction_enum import StatusTransactionEnum

class TestStatusTransactionEnum(unittest.TestCase):
    """StatusTransactionEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusTransactionEnum(self):
        """Test StatusTransactionEnum"""
        # inst = StatusTransactionEnum()

if __name__ == '__main__':
    unittest.main()
