# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.api.wallet_api import WalletApi


class TestWalletApi(unittest.TestCase):
    """WalletApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WalletApi()

    def tearDown(self) -> None:
        pass

    def test_create_wallet_users_user_id_wallet_post(self) -> None:
        """Test case for create_wallet_users_user_id_wallet_post

        Create Wallet
        """
        pass

    def test_get_wallet_users_user_id_wallet_get(self) -> None:
        """Test case for get_wallet_users_user_id_wallet_get

        Get Wallet
        """
        pass

    def test_get_wallets_integrator_user_id_invited_all_get(self) -> None:
        """Test case for get_wallets_integrator_user_id_invited_all_get

        Get Wallets
        """
        pass


if __name__ == '__main__':
    unittest.main()
