# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.api.company_api import CompanyApi


class TestCompanyApi(unittest.TestCase):
    """CompanyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompanyApi()

    def tearDown(self) -> None:
        pass

    def test_get_company_data_company_inn_info_get(self) -> None:
        """Test case for get_company_data_company_inn_info_get

        Get Company Data
        """
        pass


if __name__ == '__main__':
    unittest.main()
