# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.pagination_request_transaction_schema import PaginationRequestTransactionSchema

class TestPaginationRequestTransactionSchema(unittest.TestCase):
    """PaginationRequestTransactionSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationRequestTransactionSchema:
        """Test PaginationRequestTransactionSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationRequestTransactionSchema`
        """
        model = PaginationRequestTransactionSchema()
        if include_optional:
            return PaginationRequestTransactionSchema(
                page = 56,
                size = 56,
                total = 56,
                data = [
                    wallet_client.models.transaction_schema.TransactionSchema(
                        id = '', 
                        amount = 1.337, 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        category = 'payment services call', 
                        wallet_id = 56, 
                        status = 'processing', 
                        data = null, )
                    ]
            )
        else:
            return PaginationRequestTransactionSchema(
                page = 56,
                size = 56,
                total = 56,
                data = [
                    wallet_client.models.transaction_schema.TransactionSchema(
                        id = '', 
                        amount = 1.337, 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        category = 'payment services call', 
                        wallet_id = 56, 
                        status = 'processing', 
                        data = null, )
                    ],
        )
        """

    def testPaginationRequestTransactionSchema(self):
        """Test PaginationRequestTransactionSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
