# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.transaction_schema_refill import TransactionSchemaRefill

class TestTransactionSchemaRefill(unittest.TestCase):
    """TransactionSchemaRefill unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionSchemaRefill:
        """Test TransactionSchemaRefill
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionSchemaRefill`
        """
        model = TransactionSchemaRefill()
        if include_optional:
            return TransactionSchemaRefill(
                id = '',
                amount = 1.337,
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                category = 'payment services call',
                wallet_id = 56,
                status = 'processing',
                data = wallet_client.models.transaction_create_refill.TransactionCreateRefill(
                    invoice_id = '', 
                    invoice_number = '', 
                    inn = '', 
                    phone = '', 
                    invoice_url = '', 
                    remains = 1.337, 
                    act_url = '', ),
                acts = [
                    wallet_client.models.act_schema.ActSchema(
                        id = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'processing', 
                        amount = 1.337, )
                    ]
            )
        else:
            return TransactionSchemaRefill(
        )
        """

    def testTransactionSchemaRefill(self):
        """Test TransactionSchemaRefill"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
