# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.transaction_bonus_integrator import TransactionBonusIntegrator

class TestTransactionBonusIntegrator(unittest.TestCase):
    """TransactionBonusIntegrator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionBonusIntegrator:
        """Test TransactionBonusIntegrator
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionBonusIntegrator`
        """
        model = TransactionBonusIntegrator()
        if include_optional:
            return TransactionBonusIntegrator(
                id_user = '',
                amount = 1.337
            )
        else:
            return TransactionBonusIntegrator(
        )
        """

    def testTransactionBonusIntegrator(self):
        """Test TransactionBonusIntegrator"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
