# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.type_transaction_enum import TypeTransactionEnum

class TestTypeTransactionEnum(unittest.TestCase):
    """TypeTransactionEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypeTransactionEnum(self):
        """Test TypeTransactionEnum"""
        # inst = TypeTransactionEnum()

if __name__ == '__main__':
    unittest.main()
