# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.api.invoice_api import InvoiceApi


class TestInvoiceApi(unittest.TestCase):
    """InvoiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvoiceApi()

    def tearDown(self) -> None:
        pass

    def test_create_invoice_users_user_id_invoices_post(self) -> None:
        """Test case for create_invoice_users_user_id_invoices_post

        Create Invoice
        """
        pass

    def test_get_invoice_users_user_id_invoices_invoice_id_get(self) -> None:
        """Test case for get_invoice_users_user_id_invoices_invoice_id_get

        Get Invoice
        """
        pass


if __name__ == '__main__':
    unittest.main()
