# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.transaction_payment_services_call import TransactionPaymentServicesCall

class TestTransactionPaymentServicesCall(unittest.TestCase):
    """TransactionPaymentServicesCall unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionPaymentServicesCall:
        """Test TransactionPaymentServicesCall
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionPaymentServicesCall`
        """
        model = TransactionPaymentServicesCall()
        if include_optional:
            return TransactionPaymentServicesCall(
                id_transaction_integrator = '',
                duration = 56,
                price_second = 1.337,
                text_call = ''
            )
        else:
            return TransactionPaymentServicesCall(
        )
        """

    def testTransactionPaymentServicesCall(self):
        """Test TransactionPaymentServicesCall"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
