# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.expense_response import ExpenseResponse

class TestExpenseResponse(unittest.TestCase):
    """ExpenseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExpenseResponse:
        """Test ExpenseResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExpenseResponse`
        """
        model = ExpenseResponse()
        if include_optional:
            return ExpenseResponse(
                user_id = 56,
                amount = 1.337
            )
        else:
            return ExpenseResponse(
                user_id = 56,
                amount = 1.337,
        )
        """

    def testExpenseResponse(self):
        """Test ExpenseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
