# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.type_error_enum import TypeErrorEnum

class TestTypeErrorEnum(unittest.TestCase):
    """TypeErrorEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypeErrorEnum(self):
        """Test TypeErrorEnum"""
        # inst = TypeErrorEnum()

if __name__ == '__main__':
    unittest.main()
