# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.health_check_response import HealthCheckResponse

class TestHealthCheckResponse(unittest.TestCase):
    """HealthCheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HealthCheckResponse:
        """Test HealthCheckResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HealthCheckResponse`
        """
        model = HealthCheckResponse()
        if include_optional:
            return HealthCheckResponse(
                status = '',
                details = wallet_client.models.health_check_details_schema.HealthCheckDetailsSchema(
                    database = 'connected', 
                    redis = 'available', 
                    uptime = '', )
            )
        else:
            return HealthCheckResponse(
                status = '',
                details = wallet_client.models.health_check_details_schema.HealthCheckDetailsSchema(
                    database = 'connected', 
                    redis = 'available', 
                    uptime = '', ),
        )
        """

    def testHealthCheckResponse(self):
        """Test HealthCheckResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
