# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.statistic_by_testing_response import StatisticByTestingResponse

class TestStatisticByTestingResponse(unittest.TestCase):
    """StatisticByTestingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatisticByTestingResponse:
        """Test StatisticByTestingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatisticByTestingResponse`
        """
        model = StatisticByTestingResponse()
        if include_optional:
            return StatisticByTestingResponse(
                days_testing = 56,
                count_transactions = 56,
                average_expense = 1.337,
                expense = 1.337,
                start_data = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_data = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return StatisticByTestingResponse(
                days_testing = 56,
                count_transactions = 56,
                average_expense = 1.337,
                expense = 1.337,
                start_data = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_data = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testStatisticByTestingResponse(self):
        """Test StatisticByTestingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
