# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.api.transaction_api import TransactionApi


class TestTransactionApi(unittest.TestCase):
    """TransactionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionApi()

    def tearDown(self) -> None:
        pass

    def test_close_act_close_acts_get(self) -> None:
        """Test case for close_act_close_acts_get

        Close Act
        """
        pass

    def test_confirming_invoices_confirming_invoices_get(self) -> None:
        """Test case for confirming_invoices_confirming_invoices_get

        Confirming Invoices
        """
        pass

    def test_get_act_file_users_user_id_acts_act_id_file_post(self) -> None:
        """Test case for get_act_file_users_user_id_acts_act_id_file_post

        Get Act File
        """
        pass

    def test_get_expenses_users_user_id_expenses_get(self) -> None:
        """Test case for get_expenses_users_user_id_expenses_get

        Get Expenses
        """
        pass

    def test_get_invoice_file_users_user_id_invoice_invoice_id_file_post(self) -> None:
        """Test case for get_invoice_file_users_user_id_invoice_invoice_id_file_post

        Get Invoice File
        """
        pass

    def test_get_refills_users_user_id_refills_get(self) -> None:
        """Test case for get_refills_users_user_id_refills_get

        Get Refills
        """
        pass

    def test_get_transaction_users_user_id_transactions_transaction_id_get(self) -> None:
        """Test case for get_transaction_users_user_id_transactions_transaction_id_get

        Get Transaction
        """
        pass

    def test_get_transactions_users_user_id_transactions_get(self) -> None:
        """Test case for get_transactions_users_user_id_transactions_get

        Get Transactions
        """
        pass

    def test_payment_transaction_users_user_id_payment_transaction_post(self) -> None:
        """Test case for payment_transaction_users_user_id_payment_transaction_post

        Payment Transaction
        """
        pass

    def test_refill_transaction_users_user_id_refill_transaction_post(self) -> None:
        """Test case for refill_transaction_users_user_id_refill_transaction_post

        Refill Transaction
        """
        pass

    def test_update_transaction_users_user_id_transactions_transaction_id_put(self) -> None:
        """Test case for update_transaction_users_user_id_transactions_transaction_id_put

        Update Transaction
        """
        pass


if __name__ == '__main__':
    unittest.main()
