# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.get_api_v1_invoice_invoice_id_info_response200_status import GetApiV1InvoiceInvoiceIdInfoResponse200Status

class TestGetApiV1InvoiceInvoiceIdInfoResponse200Status(unittest.TestCase):
    """GetApiV1InvoiceInvoiceIdInfoResponse200Status unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetApiV1InvoiceInvoiceIdInfoResponse200Status(self):
        """Test GetApiV1InvoiceInvoiceIdInfoResponse200Status"""
        # inst = GetApiV1InvoiceInvoiceIdInfoResponse200Status()

if __name__ == '__main__':
    unittest.main()
