# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.transaction_create_refill import TransactionCreateRefill

class TestTransactionCreateRefill(unittest.TestCase):
    """TransactionCreateRefill unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionCreateRefill:
        """Test TransactionCreateRefill
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionCreateRefill`
        """
        model = TransactionCreateRefill()
        if include_optional:
            return TransactionCreateRefill(
                invoice_id = '',
                invoice_number = '',
                inn = '',
                phone = '',
                invoice_url = '',
                remains = 1.337,
                act_url = ''
            )
        else:
            return TransactionCreateRefill(
                invoice_id = '',
                invoice_url = '',
                remains = 1.337,
        )
        """

    def testTransactionCreateRefill(self):
        """Test TransactionCreateRefill"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
