# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet_client.models.status_database import StatusDatabase

class TestStatusDatabase(unittest.TestCase):
    """StatusDatabase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusDatabase(self):
        """Test StatusDatabase"""
        # inst = StatusDatabase()

if __name__ == '__main__':
    unittest.main()
