# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CategoryTransactionEnum(str, Enum):
    """
    CategoryTransactionEnum
    """

    """
    allowed enum values
    """
    PAYMENT_SERVICES_CALL = 'payment services call'
    PAYMENT_SERVICES_VIDEO = 'payment services video'
    REFILL = 'refill'
    BONUS_INTEGRATOR = 'bonus integrator'
    WITHDRAWAL = 'withdrawal'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CategoryTransactionEnum from a JSON string"""
        return cls(json.loads(json_str))


