# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StatusTransactionEnum(str, Enum):
    """
    StatusTransactionEnum
    """

    """
    allowed enum values
    """
    PROCESSING = 'processing'
    PROCESSING_TEST = 'processing test'
    CREATING_ACT = 'creating_act'
    COMPLETED = 'completed'
    COMPLETED_TEST = 'completed test'
    FAILED = 'failed'
    CANCELLED = 'cancelled'
    CANCELLED_TEST = 'cancelled test'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StatusTransactionEnum from a JSON string"""
        return cls(json.loads(json_str))


