# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from wallet_client.models.transaction_bonus_integrator import TransactionBonusIntegrator
from wallet_client.models.transaction_create_refill import TransactionCreateRefill
from wallet_client.models.transaction_payment_services_call import TransactionPaymentServicesCall
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

TRANSACTIONSCHEMADATA_ANY_OF_SCHEMAS = ["TransactionBonusIntegrator", "TransactionCreateRefill", "TransactionPaymentServicesCall"]

class TransactionSchemaData(BaseModel):
    """
    TransactionSchemaData
    """

    # data type: TransactionPaymentServicesCall
    anyof_schema_1_validator: Optional[TransactionPaymentServicesCall] = None
    # data type: TransactionBonusIntegrator
    anyof_schema_2_validator: Optional[TransactionBonusIntegrator] = None
    # data type: TransactionCreateRefill
    anyof_schema_3_validator: Optional[TransactionCreateRefill] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[TransactionBonusIntegrator, TransactionCreateRefill, TransactionPaymentServicesCall]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "TransactionBonusIntegrator", "TransactionCreateRefill", "TransactionPaymentServicesCall" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        if v is None:
            return v

        instance = TransactionSchemaData.model_construct()
        error_messages = []
        # validate data type: TransactionPaymentServicesCall
        if not isinstance(v, TransactionPaymentServicesCall):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TransactionPaymentServicesCall`")
        else:
            return v

        # validate data type: TransactionBonusIntegrator
        if not isinstance(v, TransactionBonusIntegrator):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TransactionBonusIntegrator`")
        else:
            return v

        # validate data type: TransactionCreateRefill
        if not isinstance(v, TransactionCreateRefill):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TransactionCreateRefill`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in TransactionSchemaData with anyOf schemas: TransactionBonusIntegrator, TransactionCreateRefill, TransactionPaymentServicesCall. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        if json_str is None:
            return instance

        error_messages = []
        # anyof_schema_1_validator: Optional[TransactionPaymentServicesCall] = None
        try:
            instance.actual_instance = TransactionPaymentServicesCall.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[TransactionBonusIntegrator] = None
        try:
            instance.actual_instance = TransactionBonusIntegrator.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[TransactionCreateRefill] = None
        try:
            instance.actual_instance = TransactionCreateRefill.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into TransactionSchemaData with anyOf schemas: TransactionBonusIntegrator, TransactionCreateRefill, TransactionPaymentServicesCall. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], TransactionBonusIntegrator, TransactionCreateRefill, TransactionPaymentServicesCall]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


