# coding: utf-8

"""
    Wallet Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class TransactionCreateRefill(BaseModel):
    """
    TransactionCreateRefill
    """ # noqa: E501
    invoice_id: StrictStr
    invoice_number: Optional[StrictStr] = ''
    inn: Optional[StrictStr] = ''
    phone: Optional[StrictStr] = ''
    invoice_url: StrictStr
    remains: Union[StrictFloat, StrictInt]
    act_url: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["invoice_id", "invoice_number", "inn", "phone", "invoice_url", "remains", "act_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionCreateRefill from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionCreateRefill from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "invoice_id": obj.get("invoice_id"),
            "invoice_number": obj.get("invoice_number") if obj.get("invoice_number") is not None else '',
            "inn": obj.get("inn") if obj.get("inn") is not None else '',
            "phone": obj.get("phone") if obj.get("phone") is not None else '',
            "invoice_url": obj.get("invoice_url"),
            "remains": obj.get("remains"),
            "act_url": obj.get("act_url") if obj.get("act_url") is not None else ''
        })
        return _obj


